name: Run Studio Crawler

on:
  schedule:
    - cron: '0 0 * * 0'  # runs every Sunday at midnight (UTC)
  workflow_dispatch: 

jobs:
  run-studio-crawler:
    runs-on: ubuntu-latest
    container:
      image: python:3.10  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Write Firebase service account to file
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ./database/serviceAccountKey.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./database/requirements.txt

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/database/serviceAccountKey.json" >> $GITHUB_ENV

      - name: Run studio crawler
        run: |
          python ./database/studio_crawler.py
